"""geographic network

Revision ID: 412dd00706e2
Revises: bc3a0c7d2d6f
Create Date: 2026-09-24 00:57:08.011236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '412dd00706e2'
down_revision: Union[str, Sequence[str], None] = 'bc3a0c7d2d6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_edges',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['infrastructure_objects.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['infrastructure_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_edges_source_id'), 'network_edges', ['source_id'], unique=False)
    op.create_index(op.f('ix_network_edges_target_id'), 'network_edges', ['target_id'], unique=False)
    op.add_column('infrastructure_objects', sa.Column('district', sa.String(length=80), server_default='', nullable=False))
    op.add_column('infrastructure_objects', sa.Column('object_type', sa.String(length=32), server_default='collector', nullable=False))
    op.add_column('infrastructure_objects', sa.Column('status', sa.String(length=16), server_default='normal', nullable=False))
    op.add_column('infrastructure_objects', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('infrastructure_objects', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('infrastructure_objects', sa.Column('is_demo', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.alter_column('infrastructure_objects', 'district', server_default=None)
    op.alter_column('infrastructure_objects', 'object_type', server_default=None)
    op.alter_column('infrastructure_objects', 'status', server_default=None)
    op.alter_column('infrastructure_objects', 'is_demo', server_default=None)
    op.alter_column('telemetry_events', 'import_batch_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telemetry_events', 'import_batch_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_column('infrastructure_objects', 'is_demo')
    op.drop_column('infrastructure_objects', 'longitude')
    op.drop_column('infrastructure_objects', 'latitude')
    op.drop_column('infrastructure_objects', 'status')
    op.drop_column('infrastructure_objects', 'object_type')
    op.drop_column('infrastructure_objects', 'district')
    op.drop_index(op.f('ix_network_edges_target_id'), table_name='network_edges')
    op.drop_index(op.f('ix_network_edges_source_id'), table_name='network_edges')
    op.drop_table('network_edges')
    # ### end Alembic commands ###
